// SPDX-License-Identifier: AGPL-3.0-or-later
package core

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// MotesIndexFilename is the canonical name of the cross-agent motes index file
// generated under the global memory root.
const MotesIndexFilename = "MOTES.md"

// GenerateMotesIndex builds <globalRoot>/MOTES.md — a one-line-per-mote index
// for non-Claude agents (Codex, Gemini) that don't share Claude's MEMORY.md
// auto-memory mechanism.
//
// The format mirrors MEMORY.md's role: title, link to the node file, and a
// short description hook drawn from the first non-empty line of the body.
// Motes are grouped by type and sorted alphabetically by title within each
// group. Claude reads it via instruction in CLAUDE.md; Codex via instruction
// in AGENTS.md; Gemini via @-import in motes-shim.md.
func GenerateMotesIndex(globalRoot string) error {
	nodesDir := filepath.Join(globalRoot, "nodes")
	entries, err := os.ReadDir(nodesDir)
	if err != nil {
		if os.IsNotExist(err) {
			return writeIndex(globalRoot, nil)
		}
		return fmt.Errorf("read nodes dir: %w", err)
	}

	var motes []*Mote
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		m, err := ParseMote(filepath.Join(nodesDir, e.Name()))
		if err != nil {
			continue // skip malformed; same posture as ReadAllParallel
		}
		// Skip tombstones (forwarded motes) and soft-deleted.
		if m.ForwardedTo != "" || m.DeletedAt != nil {
			continue
		}
		motes = append(motes, m)
	}

	return writeIndex(globalRoot, motes)
}

func writeIndex(globalRoot string, motes []*Mote) error {
	if err := os.MkdirAll(globalRoot, 0755); err != nil {
		return fmt.Errorf("create global root: %w", err)
	}

	// Group by type, then sort each group by title.
	byType := map[string][]*Mote{}
	for _, m := range motes {
		byType[m.Type] = append(byType[m.Type], m)
	}
	types := make([]string, 0, len(byType))
	for t := range byType {
		types = append(types, t)
	}
	sort.Strings(types)
	for _, t := range types {
		sort.Slice(byType[t], func(i, j int) bool {
			return strings.ToLower(byType[t][i].Title) < strings.ToLower(byType[t][j].Title)
		})
	}

	var b strings.Builder
	b.WriteString("# Motes Memory Index\n\n")
	b.WriteString("Cross-agent shared knowledge graph. Generated by `mote dream` and `mote onboard`.\n")
	b.WriteString("Each entry links to a mote in `nodes/`. Status, links, and full body live in the file.\n\n")

	if len(motes) == 0 {
		b.WriteString("_(no motes yet — run `mote add` to create one)_\n")
	}

	for _, t := range types {
		fmt.Fprintf(&b, "## %s\n\n", strings.Title(t))
		for _, m := range byType[t] {
			line := indexLine(m)
			b.WriteString(line)
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	return AtomicWrite(filepath.Join(globalRoot, MotesIndexFilename), []byte(b.String()), 0644)
}

// indexLine renders one mote as `- [title](nodes/<id>.md) — <hook>`.
// Caps the line at ~200 chars to keep MOTES.md readable when loaded in agent
// context.
func indexLine(m *Mote) string {
	hook := bodyHook(m.Body)
	title := m.Title
	if title == "" {
		title = m.ID
	}
	rel := filepath.Join("nodes", m.ID+".md")
	line := fmt.Sprintf("- [%s](%s)", title, rel)
	if hook != "" {
		line += " — " + hook
	}
	return truncateLine(line, 200)
}

// bodyHook returns the first non-empty, non-heading line of body, trimmed of
// markdown noise and shortened to ~120 chars.
func bodyHook(body string) string {
	for _, line := range strings.Split(body, "\n") {
		s := strings.TrimSpace(line)
		if s == "" {
			continue
		}
		if strings.HasPrefix(s, "#") {
			continue
		}
		// Drop common bullet prefixes.
		s = strings.TrimPrefix(s, "- ")
		s = strings.TrimPrefix(s, "* ")
		// Strip simple inline markdown emphasis.
		s = strings.ReplaceAll(s, "**", "")
		s = strings.ReplaceAll(s, "__", "")
		if len(s) > 120 {
			s = s[:117] + "..."
		}
		return s
	}
	return ""
}

func truncateLine(s string, max int) string {
	if len(s) <= max {
		return s
	}
	return s[:max-3] + "..."
}
